/*
Package gostruct is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was true
in this case).

This package was generated by /Users/cmo/.gvm/pkgsets/go1.10.2/global/src/github.com/openconfig/ygot/ygen/commongen.go
using the following YANG input files:
	- github.com/openconfig/public/release/models/interfaces/openconfig-if-aggregate.yang
	- github.com/openconfig/public/release/models/interfaces/openconfig-if-ethernet.yang
	- github.com/openconfig/public/release/models/interfaces/openconfig-interfaces.yang
	- github.com/openconfig/public/release/models/lldp/openconfig-lldp.yang
	- github.com/openconfig/public/release/models/network-instance/openconfig-network-instance.yang
	- github.com/openconfig/public/release/models/platform/openconfig-platform.yang
	- github.com/openconfig/public/release/models/system/openconfig-system.yang
	- github.com/openconfig/public/release/models/vlan/openconfig-vlan.yang
Imported modules were sourced from:
	- github.com/openconfig/public/...
	- github.com/YangModels/yang/...
*/
package gostruct


// Device represents the /device YANG schema element.
type Device struct {
	Acl	*Acl	`path:"acl" module:"openconfig-acl"`
	Bgp	*Bgp	`path:"bgp" module:"openconfig-bgp"`
	Component	map[string]*Component	`path:"components/component" module:"openconfig-platform"`
	Interface	map[string]*Interface	`path:"interfaces/interface" module:"openconfig-interfaces"`
	Lldp	*Lldp	`path:"lldp" module:"openconfig-lldp"`
	LocalRoutes	*LocalRoutes	`path:"local-routes" module:"openconfig-local-routing"`
	Mpls	*Mpls	`path:"mpls" module:"openconfig-mpls"`
	NetworkInstance	map[string]*NetworkInstance	`path:"network-instances/network-instance" module:"openconfig-network-instance"`
	RoutingPolicy	*RoutingPolicy	`path:"routing-policy" module:"openconfig-routing-policy"`
	System	*System	`path:"system" module:"openconfig-system"`
}

// IsYANGGoStruct ensures that Device implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Device) IsYANGGoStruct() {}


