/*
Package gostruct is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was true
in this case).

This package was generated by /Users/cmo/.gvm/pkgsets/go1.10.2/global/src/github.com/openconfig/ygot/ygen/commongen.go
using the following YANG input files:
	- github.com/openconfig/public/release/models/interfaces/openconfig-if-aggregate.yang
	- github.com/openconfig/public/release/models/interfaces/openconfig-if-ethernet.yang
	- github.com/openconfig/public/release/models/interfaces/openconfig-interfaces.yang
	- github.com/openconfig/public/release/models/lldp/openconfig-lldp.yang
	- github.com/openconfig/public/release/models/network-instance/openconfig-network-instance.yang
	- github.com/openconfig/public/release/models/platform/openconfig-platform.yang
	- github.com/openconfig/public/release/models/system/openconfig-system.yang
	- github.com/openconfig/public/release/models/vlan/openconfig-vlan.yang
Imported modules were sourced from:
	- github.com/openconfig/public/...
	- github.com/YangModels/yang/...
*/
package gostruct


// RoutingPolicy represents the /openconfig-routing-policy/routing-policy YANG schema element.
type RoutingPolicy struct {
	DefinedSets	*RoutingPolicy_DefinedSets	`path:"defined-sets" module:"openconfig-routing-policy"`
	PolicyDefinition	map[string]*RoutingPolicy_PolicyDefinition	`path:"policy-definitions/policy-definition" module:"openconfig-routing-policy"`
}

// IsYANGGoStruct ensures that RoutingPolicy implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*RoutingPolicy) IsYANGGoStruct() {}


// RoutingPolicy_DefinedSets represents the /openconfig-routing-policy/routing-policy/defined-sets YANG schema element.
type RoutingPolicy_DefinedSets struct {
	NeighborSet	map[string]*RoutingPolicy_DefinedSets_NeighborSet	`path:"neighbor-sets/neighbor-set" module:"openconfig-routing-policy"`
	PrefixSet	map[string]*RoutingPolicy_DefinedSets_PrefixSet	`path:"prefix-sets/prefix-set" module:"openconfig-routing-policy"`
	TagSet	map[string]*RoutingPolicy_DefinedSets_TagSet	`path:"tag-sets/tag-set" module:"openconfig-routing-policy"`
}

// IsYANGGoStruct ensures that RoutingPolicy_DefinedSets implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*RoutingPolicy_DefinedSets) IsYANGGoStruct() {}


// RoutingPolicy_DefinedSets_NeighborSet represents the /openconfig-routing-policy/routing-policy/defined-sets/neighbor-sets/neighbor-set YANG schema element.
type RoutingPolicy_DefinedSets_NeighborSet struct {
	Address	[]string	`path:"config/address" module:"openconfig-routing-policy"`
	Name	*string	`path:"config/name|name" module:"openconfig-routing-policy"`
}

// IsYANGGoStruct ensures that RoutingPolicy_DefinedSets_NeighborSet implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*RoutingPolicy_DefinedSets_NeighborSet) IsYANGGoStruct() {}


// RoutingPolicy_DefinedSets_PrefixSet represents the /openconfig-routing-policy/routing-policy/defined-sets/prefix-sets/prefix-set YANG schema element.
type RoutingPolicy_DefinedSets_PrefixSet struct {
	Mode	E_OpenconfigRoutingPolicy_PrefixSet_Mode	`path:"config/mode" module:"openconfig-routing-policy"`
	Name	*string	`path:"config/name|name" module:"openconfig-routing-policy"`
	Prefix	map[RoutingPolicy_DefinedSets_PrefixSet_Prefix_Key]*RoutingPolicy_DefinedSets_PrefixSet_Prefix	`path:"prefixes/prefix" module:"openconfig-routing-policy"`
}

// IsYANGGoStruct ensures that RoutingPolicy_DefinedSets_PrefixSet implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*RoutingPolicy_DefinedSets_PrefixSet) IsYANGGoStruct() {}

// RoutingPolicy_DefinedSets_PrefixSet_Prefix_Key represents the key for list Prefix of element /openconfig-routing-policy/routing-policy/defined-sets/prefix-sets/prefix-set.
type RoutingPolicy_DefinedSets_PrefixSet_Prefix_Key struct {
	IpPrefix	string	`path:"ip-prefix"`
	MasklengthRange	string	`path:"masklength-range"`
}


// RoutingPolicy_DefinedSets_PrefixSet_Prefix represents the /openconfig-routing-policy/routing-policy/defined-sets/prefix-sets/prefix-set/prefixes/prefix YANG schema element.
type RoutingPolicy_DefinedSets_PrefixSet_Prefix struct {
	IpPrefix	*string	`path:"config/ip-prefix|ip-prefix" module:"openconfig-routing-policy"`
	MasklengthRange	*string	`path:"config/masklength-range|masklength-range" module:"openconfig-routing-policy"`
}

// IsYANGGoStruct ensures that RoutingPolicy_DefinedSets_PrefixSet_Prefix implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*RoutingPolicy_DefinedSets_PrefixSet_Prefix) IsYANGGoStruct() {}


// RoutingPolicy_DefinedSets_TagSet represents the /openconfig-routing-policy/routing-policy/defined-sets/tag-sets/tag-set YANG schema element.
type RoutingPolicy_DefinedSets_TagSet struct {
	Name	*string	`path:"config/name|name" module:"openconfig-routing-policy"`
	TagValue	[]RoutingPolicy_DefinedSets_TagSet_TagValue_Union	`path:"config/tag-value" module:"openconfig-routing-policy"`
}

// IsYANGGoStruct ensures that RoutingPolicy_DefinedSets_TagSet implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*RoutingPolicy_DefinedSets_TagSet) IsYANGGoStruct() {}


// RoutingPolicy_PolicyDefinition represents the /openconfig-routing-policy/routing-policy/policy-definitions/policy-definition YANG schema element.
type RoutingPolicy_PolicyDefinition struct {
	Name	*string	`path:"config/name|name" module:"openconfig-routing-policy"`
	Statement	map[string]*RoutingPolicy_PolicyDefinition_Statement	`path:"statements/statement" module:"openconfig-routing-policy"`
}

// IsYANGGoStruct ensures that RoutingPolicy_PolicyDefinition implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*RoutingPolicy_PolicyDefinition) IsYANGGoStruct() {}


// RoutingPolicy_PolicyDefinition_Statement represents the /openconfig-routing-policy/routing-policy/policy-definitions/policy-definition/statements/statement YANG schema element.
type RoutingPolicy_PolicyDefinition_Statement struct {
	Actions	*RoutingPolicy_PolicyDefinition_Statement_Actions	`path:"actions" module:"openconfig-routing-policy"`
	Conditions	*RoutingPolicy_PolicyDefinition_Statement_Conditions	`path:"conditions" module:"openconfig-routing-policy"`
	Name	*string	`path:"config/name|name" module:"openconfig-routing-policy"`
}

// IsYANGGoStruct ensures that RoutingPolicy_PolicyDefinition_Statement implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*RoutingPolicy_PolicyDefinition_Statement) IsYANGGoStruct() {}


// RoutingPolicy_PolicyDefinition_Statement_Actions represents the /openconfig-routing-policy/routing-policy/policy-definitions/policy-definition/statements/statement/actions YANG schema element.
type RoutingPolicy_PolicyDefinition_Statement_Actions struct {
	PolicyResult	E_OpenconfigRoutingPolicy_PolicyResultType	`path:"config/policy-result" module:"openconfig-routing-policy"`
}

// IsYANGGoStruct ensures that RoutingPolicy_PolicyDefinition_Statement_Actions implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*RoutingPolicy_PolicyDefinition_Statement_Actions) IsYANGGoStruct() {}


// RoutingPolicy_PolicyDefinition_Statement_Conditions represents the /openconfig-routing-policy/routing-policy/policy-definitions/policy-definition/statements/statement/conditions YANG schema element.
type RoutingPolicy_PolicyDefinition_Statement_Conditions struct {
	CallPolicy	*string	`path:"config/call-policy" module:"openconfig-routing-policy"`
	InstallProtocolEq	E_OpenconfigPolicyTypes_INSTALL_PROTOCOL_TYPE	`path:"config/install-protocol-eq" module:"openconfig-routing-policy"`
	MatchInterface	*RoutingPolicy_PolicyDefinition_Statement_Conditions_MatchInterface	`path:"match-interface" module:"openconfig-routing-policy"`
	MatchNeighborSet	*RoutingPolicy_PolicyDefinition_Statement_Conditions_MatchNeighborSet	`path:"match-neighbor-set" module:"openconfig-routing-policy"`
	MatchPrefixSet	*RoutingPolicy_PolicyDefinition_Statement_Conditions_MatchPrefixSet	`path:"match-prefix-set" module:"openconfig-routing-policy"`
	MatchTagSet	*RoutingPolicy_PolicyDefinition_Statement_Conditions_MatchTagSet	`path:"match-tag-set" module:"openconfig-routing-policy"`
}

// IsYANGGoStruct ensures that RoutingPolicy_PolicyDefinition_Statement_Conditions implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*RoutingPolicy_PolicyDefinition_Statement_Conditions) IsYANGGoStruct() {}


// RoutingPolicy_PolicyDefinition_Statement_Conditions_MatchInterface represents the /openconfig-routing-policy/routing-policy/policy-definitions/policy-definition/statements/statement/conditions/match-interface YANG schema element.
type RoutingPolicy_PolicyDefinition_Statement_Conditions_MatchInterface struct {
	Interface	*string	`path:"config/interface" module:"openconfig-routing-policy"`
	Subinterface	*uint32	`path:"config/subinterface" module:"openconfig-routing-policy"`
}

// IsYANGGoStruct ensures that RoutingPolicy_PolicyDefinition_Statement_Conditions_MatchInterface implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*RoutingPolicy_PolicyDefinition_Statement_Conditions_MatchInterface) IsYANGGoStruct() {}


// RoutingPolicy_PolicyDefinition_Statement_Conditions_MatchNeighborSet represents the /openconfig-routing-policy/routing-policy/policy-definitions/policy-definition/statements/statement/conditions/match-neighbor-set YANG schema element.
type RoutingPolicy_PolicyDefinition_Statement_Conditions_MatchNeighborSet struct {
	MatchSetOptions	E_OpenconfigRoutingPolicy_MatchSetOptionsRestrictedType	`path:"config/match-set-options" module:"openconfig-routing-policy"`
	NeighborSet	*string	`path:"config/neighbor-set" module:"openconfig-routing-policy"`
}

// IsYANGGoStruct ensures that RoutingPolicy_PolicyDefinition_Statement_Conditions_MatchNeighborSet implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*RoutingPolicy_PolicyDefinition_Statement_Conditions_MatchNeighborSet) IsYANGGoStruct() {}


// RoutingPolicy_PolicyDefinition_Statement_Conditions_MatchPrefixSet represents the /openconfig-routing-policy/routing-policy/policy-definitions/policy-definition/statements/statement/conditions/match-prefix-set YANG schema element.
type RoutingPolicy_PolicyDefinition_Statement_Conditions_MatchPrefixSet struct {
	MatchSetOptions	E_OpenconfigRoutingPolicy_MatchSetOptionsRestrictedType	`path:"config/match-set-options" module:"openconfig-routing-policy"`
	PrefixSet	*string	`path:"config/prefix-set" module:"openconfig-routing-policy"`
}

// IsYANGGoStruct ensures that RoutingPolicy_PolicyDefinition_Statement_Conditions_MatchPrefixSet implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*RoutingPolicy_PolicyDefinition_Statement_Conditions_MatchPrefixSet) IsYANGGoStruct() {}


// RoutingPolicy_PolicyDefinition_Statement_Conditions_MatchTagSet represents the /openconfig-routing-policy/routing-policy/policy-definitions/policy-definition/statements/statement/conditions/match-tag-set YANG schema element.
type RoutingPolicy_PolicyDefinition_Statement_Conditions_MatchTagSet struct {
	MatchSetOptions	E_OpenconfigRoutingPolicy_MatchSetOptionsRestrictedType	`path:"config/match-set-options" module:"openconfig-routing-policy"`
	TagSet	*string	`path:"config/tag-set" module:"openconfig-routing-policy"`
}

// IsYANGGoStruct ensures that RoutingPolicy_PolicyDefinition_Statement_Conditions_MatchTagSet implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*RoutingPolicy_PolicyDefinition_Statement_Conditions_MatchTagSet) IsYANGGoStruct() {}


